version: '3.2'

services:

  mongo-logs:
    image: mongo
    ports:
      - "27020:27017"
    volumes:
      - type: volume
        source: ./mongo-logs
        target: /data/db

  messenger:
    build: ./arnaux

  sandbox-service:
    depends_on:
      - messenger
    build: ./zandbak-service
    environment:
      - remote_uri=ws://messenger:3000
      - zandbakConfig_sand=lodash/subworkers
      - zandbakConfig_backend=electron
      - ELECTRON_ENABLE_LOGGING=1
      - logLevel=+perf,+error,+info

  mongo-state:
    image: mongo
    ports:
      - "27018:27017"

  state-service:
    depends_on:
      - mongo-state
      - messenger
    build: ./redemption
    environment:
      - redemption_environment=prod

  mongo-front-service:
    image: mongo
    ports:
      - "27019:27017"

  front-service:
    depends_on:
      - mongo-logs
      - mongo-front-service
      - messenger
    build: ./front-service
    volumes:
      - type: volume
        source: ./front-service/logs
        target: /front-end-service/logs
    environment:
      - DB_URI=mongodb://mongo-front-service/fe-db
      - ARNAUX_URL=ws://messenger:3000
      - GUNSLINGERS=true
      - LOG_LEVEL=info
      - LOG_DBURI=mongodb://mongo-logs/qd-logs
    ports:
      - "3000:3000"
      - "3001:3001"

  init-service:
    depends_on:
      - state-service
      - front-service
    build: ./ignition
